// Agentarium mock data — plans, messages, decisions, roles, verdicts.
// Tasks come from window.PROJECT_DATA (data.js) — Khira keeps owning them.
(function () {
  const NOW = "2026-05-27T11:14:00Z";

  // ─── Roles / Crews ─────────────────────────────────────────────────────
  const ROLES = [
    {
      id: "human-raj",
      name: "Raj Kumar",
      title: "Human operator",
      kind: "human",
      hue: 50,             // warm orange
      glyph: "RK",
      status: "on-station",
      description:
        "Final human owner. Sets product direction, approves Ledger decisions, and arbitrates verdicts when agents disagree.",
      responsibilities: [
        "Approve / reject final verdicts",
        "Resolve agent stand-offs",
        "Sign off product direction",
      ],
      permissions: ["sign-off", "supersede", "delete", "approve-write"],
      lastSeen: "2026-05-27T11:12:00Z",
      tasks: 4,
      pending: 6,
    },
    {
      id: "sdp",
      name: "SDP",
      title: "Senior Director of Product",
      kind: "agent",
      hue: 300,            // violet
      glyph: "SD",
      status: "on-station",
      description:
        "Owns product strategy and outward-facing direction. Writes product memos through Signal Courier and approves Plans.",
      responsibilities: [
        "Author product direction memos",
        "Approve Plans before they enter execution",
        "Escalate verdicts to Raj",
      ],
      permissions: ["author-plan", "approve-plan", "send-memo"],
      lastSeen: "2026-05-27T10:48:00Z",
      tasks: 2,
      pending: 3,
    },
    {
      id: "spm",
      name: "SPM",
      title: "Senior Product Manager",
      kind: "agent",
      hue: 195,            // teal
      glyph: "PM",
      status: "on-station",
      description:
        "Shapes the work. Converts plans into Khira tasks, accepts or rejects engineering output, runs the verdict queue.",
      responsibilities: [
        "Cut Khira tickets from Plan checklists",
        "Triage incoming Signal Courier messages",
        "Mark verdicts: needs-review → done / rejected",
      ],
      permissions: ["create-task", "verdict", "supersede-plan"],
      lastSeen: "2026-05-27T11:08:00Z",
      tasks: 11,
      pending: 9,
    },
    {
      id: "tl",
      name: "TL",
      title: "Tech Lead",
      kind: "agent",
      hue: 260,            // indigo
      glyph: "TL",
      status: "off-station",
      description:
        "Architecture, engineering review, risk assessment. Verdicts engineering output and proposes refactors.",
      responsibilities: [
        "Review FE/BE code-state",
        "Architecture sign-off",
        "Cleanup / debt ledgers",
      ],
      permissions: ["verdict", "create-task", "block"],
      lastSeen: "2026-05-26T22:14:00Z",
      tasks: 5,
      pending: 4,
    },
    {
      id: "fe",
      name: "FE",
      title: "Frontend Agent",
      kind: "agent",
      hue: 220,            // cyan
      glyph: "FE",
      status: "in-task",
      description:
        "Implements frontend work assigned by TL. Sends completion handoffs through Signal Courier.",
      responsibilities: ["Frontend implementation", "Self-test", "Send completion handoffs"],
      permissions: ["update-task", "send-handoff"],
      lastSeen: "2026-05-27T11:13:00Z",
      tasks: 7,
      pending: 0,
    },
    {
      id: "be",
      name: "BE",
      title: "Backend / Data Agent",
      kind: "agent",
      hue: 150,            // green
      glyph: "BE",
      status: "in-task",
      description:
        "Owns backend, data loaders, schema, APIs. Handoffs go to TL/SPM for verdict.",
      responsibilities: ["Backend services", "Data pipelines", "Schema + migrations"],
      permissions: ["update-task", "send-handoff"],
      lastSeen: "2026-05-27T11:05:00Z",
      tasks: 9,
      pending: 1,
    },
  ];

  // ─── Plans ─────────────────────────────────────────────────────────────
  const PLANS = [
    {
      id: "PL-04",
      phase: "p4",
      title: "Phase 4 — Agent Workspace",
      path: "plans/2026-05-27_phase4-agent-workspace.md",
      status: "active",
      author: "sdp",
      reviewers: ["spm", "tl"],
      verdict: "needs-review",
      checklist: { done: 4, total: 11 },
      linkedTasks: 6,
      linkedMessages: 3,
      linkedDecisions: 1,
      updated: "2026-05-27T09:42:00Z",
      summary:
        "Move from Khira-only task tracking to a full agent workspace. Adds Planroom, Signal Courier, Ledgers, Crews, Verdicts on top of existing Khira.",
      sections: [
        { id: "p4-1", title: "Product shell rename → Agentarium", done: true },
        { id: "p4-2", title: "Module IA + navigation model", done: true },
        { id: "p4-3", title: "Planroom — plan reader, status, linking", done: false },
        { id: "p4-4", title: "Signal Courier — message ledger + routing", done: false },
        { id: "p4-5", title: "Ledgers — durable decision records", done: false },
        { id: "p4-6", title: "Crews — role stations + Acting-as", done: true },
        { id: "p4-7", title: "Verdicts — gates + stamps inline", done: false },
        { id: "p4-8", title: "Local-folder source mode (read)", done: true },
        { id: "p4-9", title: "Local-folder source mode (structured save)", done: false },
        { id: "p4-10", title: "API workspace mode contracts", done: false },
        { id: "p4-11", title: "Pilot dogfood on Digital Twin project", done: false },
      ],
    },
    {
      id: "PL-03",
      phase: "p3",
      title: "Phase 3 — Trust, Persona & ML",
      path: "plans/2026-05-22_phase3-trust-persona.md",
      status: "active",
      author: "sdp",
      reviewers: ["tl", "human-raj"],
      verdict: "done",
      checklist: { done: 9, total: 17 },
      linkedTasks: 5,
      linkedMessages: 4,
      linkedDecisions: 3,
      updated: "2026-05-22T19:00:00Z",
      summary:
        "Stabilize foundation. Add RBAC + persona-scoped agent prompts. Ask-agent gains relevance gate and references-as-cards.",
      sections: [
        { id: "p3-1", title: "Stabilize foundation (close carry-overs)", done: false },
        { id: "p3-2", title: "Persona / RBAC foundation", done: false },
        { id: "p3-3", title: "Ask-agent intelligence", done: false },
      ],
    },
    {
      id: "PL-02",
      phase: "p2",
      title: "Phase 2 — Agentic Monitoring (Demo 1)",
      path: "plans/2026-05-18_phase2-demo1.md",
      status: "shipped",
      author: "sdp",
      reviewers: ["tl", "spm"],
      verdict: "done",
      checklist: { done: 24, total: 24 },
      linkedTasks: 49,
      linkedMessages: 11,
      linkedDecisions: 4,
      updated: "2026-05-21T08:51:00Z",
      summary:
        "AgentHome chat-first surface + OpenAI SDK multi-agent. Foundation for demo 1 with J&J.",
      sections: [{ id: "p2-1", title: "Demo 1 — chat + 1-line live strip", done: true }],
    },
    {
      id: "PL-AR-01",
      phase: "p2",
      title: "Architecture pivot — AutoGen → OpenAI SDK",
      path: "plans/2026-05-18_arch-pivot.md",
      status: "superseded",
      author: "tl",
      reviewers: ["sdp"],
      verdict: "superseded",
      checklist: { done: 6, total: 6 },
      linkedTasks: 8,
      linkedMessages: 2,
      linkedDecisions: 1,
      updated: "2026-05-19T13:57:00Z",
      summary:
        "Original plan to use Microsoft AutoGen. Superseded after CTO review — moved to OpenAI SDK + MAF-inspired patterns.",
      sections: [],
    },
  ];

  // ─── Signal Courier — messages ─────────────────────────────────────────
  const MESSAGES = [
    {
      id: "MSG-2026-05-27-1200",
      phase: "p4",
      subject: "Design the Agentarium UI as a creative project command center",
      from: "sdp",
      to: "human-raj",            // routed to the designer (Raj acting as product designer here)
      via: ["spm"],
      date: "2026-05-27T12:00:00Z",
      kind: "product-direction",
      re: null,
      status: "actioned",
      verdict: "needs-review",
      linkedPlan: "PL-04",
      linkedTasks: [],
      linkedDecisions: ["DEC-04"],
      preview:
        "Please design Agentarium as a creative, local-first project command center for human-led AI-agent teams, with room to invent a new interaction model …",
      nextActions: [
        "Information architecture for Agentarium",
        "Wireframes / hi-fi mocks for 7 modules",
        "Detail panels for task / plan / message / decision / role / verdict",
        "Creative visual direction",
      ],
    },
    {
      id: "MSG-2026-05-27-0942",
      phase: "p4",
      subject: "Phase 4 plan attached — please review by EOD",
      from: "sdp",
      to: "spm",
      via: [],
      date: "2026-05-27T09:42:00Z",
      kind: "review-request",
      re: null,
      status: "unread",
      verdict: "needs-review",
      linkedPlan: "PL-04",
      linkedTasks: [],
      linkedDecisions: [],
      preview:
        "First draft of phase 4 plan. Six modules; Khira stays. Need a verdict before TL scopes the work.",
      nextActions: ["Read PL-04", "Mark verdict on plan"],
    },
    {
      id: "MSG-2026-05-26-2214",
      phase: "p3",
      subject: "Re: agent_runner f-string crash — fixed",
      from: "be",
      to: "tl",
      via: ["spm"],
      date: "2026-05-26T22:14:00Z",
      kind: "handoff",
      re: "MSG-2026-05-26-1840",
      status: "actioned",
      verdict: "tested",
      linkedPlan: "PL-03",
      linkedTasks: ["W1.5"],
      linkedDecisions: [],
      preview:
        "Patched f-string in agent_runner.py and bumped model id to gpt-5.4. Replayed two batches end-to-end; both passed.",
      nextActions: ["Mark W1.5 as tested"],
    },
    {
      id: "MSG-2026-05-26-1840",
      phase: "p3",
      subject: "Bug: ask-agent endpoint 500s on every call",
      from: "spm",
      to: "be",
      via: ["tl"],
      date: "2026-05-26T18:40:00Z",
      kind: "handoff",
      re: null,
      status: "archived",
      verdict: "done",
      linkedPlan: "PL-03",
      linkedTasks: ["W1.5"],
      linkedDecisions: [],
      preview:
        "Senior QA pass found agent_runner.py crashes on every call. Two defects: f-string nested quotes, model id stale.",
      nextActions: [],
    },
    {
      id: "MSG-2026-05-22-1500",
      phase: "p3",
      subject: "Phase 3 plan — Stabilize / RBAC / Ask-agent",
      from: "sdp",
      to: "spm",
      via: [],
      date: "2026-05-22T15:00:00Z",
      kind: "product-direction",
      re: null,
      status: "actioned",
      verdict: "done",
      linkedPlan: "PL-03",
      linkedTasks: [],
      linkedDecisions: ["DEC-03"],
      preview:
        "Three stages. P3.1 sequential. P3.2 + P3.3 parallel. Persona scope flows into specialist agent prompts.",
      nextActions: ["Cut tickets P3.1.1–P3.1.5", "Cut tickets P3.2.x", "Cut tickets P3.3.x"],
    },
    {
      id: "MSG-2026-05-19-1357",
      phase: "p2",
      subject: "Azure OpenAI migration — deployment gpt-5.4 wired in",
      from: "be",
      to: "tl",
      via: [],
      date: "2026-05-19T13:57:00Z",
      kind: "handoff",
      re: null,
      status: "actioned",
      verdict: "tested",
      linkedPlan: "PL-02",
      linkedTasks: ["A2.2"],
      linkedDecisions: ["DEC-02"],
      preview:
        "Moved LLM client from direct OpenAI to Azure OpenAI provider via build_llm_client() factory. Streaming, tool-calling, validation unchanged.",
      nextActions: [],
    },
    {
      id: "MSG-2026-05-18-1730",
      phase: "p2",
      subject: "Architecture pivot — AutoGen → OpenAI SDK (MAF patterns)",
      from: "tl",
      to: "sdp",
      via: [],
      date: "2026-05-18T17:30:00Z",
      kind: "product-direction",
      re: null,
      status: "actioned",
      verdict: "done",
      linkedPlan: "PL-AR-01",
      linkedTasks: ["A2.2"],
      linkedDecisions: ["DEC-02"],
      preview:
        "Moving off AutoGen. Use OpenAI SDK directly with MAF-inspired multi-agent patterns. Patterns are hand-rolled on AsyncOpenAI.",
      nextActions: ["Supersede PL-AR-01", "Update A2.2 description"],
    },
  ];

  // ─── Ledgers — decisions ──────────────────────────────────────────────
  const DECISIONS = [
    {
      id: "DEC-04",
      phase: "p4",
      title: "Agentarium becomes the product shell; Khira is one module",
      decidedBy: "human-raj",
      witnesses: ["sdp", "spm"],
      at: "2026-05-26T19:13:00Z",
      status: "active",
      verdict: "approved",
      why:
        "Khira's vocabulary (tasks / reviews / PM verdicts) does not cover plans, messages, decisions, or roles. The product is increasingly about orchestrating agent teams, not tracking tickets.",
      options: [
        { label: "Keep Khira name; bolt new modules on", chosen: false },
        { label: "Rename top-level shell → Agentarium; nest Khira", chosen: true },
        { label: "Spin a sibling product", chosen: false },
      ],
      affects: { plans: ["PL-04"], tasks: 0, messages: 1 },
      seal: "RAJ · 2026-05-26",
    },
    {
      id: "DEC-03",
      phase: "p3",
      title: "Persona scope flows into specialist agent system prompts",
      decidedBy: "sdp",
      witnesses: ["tl"],
      at: "2026-05-22T15:00:00Z",
      status: "active",
      verdict: "approved",
      why:
        "RBAC at API layer alone leaks scope. Specialists must see persona_id and tailor responses accordingly. Cheap to add now, expensive later.",
      options: [
        { label: "API-layer RBAC only", chosen: false },
        { label: "Persona_id in system prompt of every specialist", chosen: true },
      ],
      affects: { plans: ["PL-03"], tasks: 5, messages: 1 },
      seal: "SDP · 2026-05-22",
    },
    {
      id: "DEC-02",
      phase: "p2",
      title: "Use OpenAI SDK + MAF-inspired patterns, not Microsoft AutoGen",
      decidedBy: "tl",
      witnesses: ["sdp", "human-raj"],
      at: "2026-05-18T17:30:00Z",
      status: "active",
      verdict: "approved",
      why:
        "AutoGen abstractions add cost without earning their place; we already need fine-grained tool-call streaming. Hand-rolled patterns over AsyncOpenAI give the same multi-agent shape with less surface area.",
      options: [
        { label: "Microsoft AutoGen", chosen: false },
        { label: "Microsoft Agent Framework", chosen: false },
        { label: "OpenAI SDK + MAF-inspired patterns", chosen: true },
      ],
      affects: { plans: ["PL-02", "PL-AR-01"], tasks: 8, messages: 2 },
      seal: "TL · 2026-05-18",
    },
    {
      id: "DEC-01",
      phase: "p1",
      title: "DuckDB replaces TimescaleDB",
      decidedBy: "tl",
      witnesses: ["be", "human-raj"],
      at: "2026-05-13T14:00:00Z",
      status: "active",
      verdict: "approved",
      why:
        "Single-file embedded DB matches the local-first posture and removes a docker service. Idempotent init via IF NOT EXISTS verified.",
      options: [
        { label: "TimescaleDB", chosen: false },
        { label: "DuckDB file-based", chosen: true },
        { label: "SQLite + JSON columns", chosen: false },
      ],
      affects: { plans: ["PL-02"], tasks: 12, messages: 0 },
      seal: "TL · 2026-05-13",
    },
    {
      id: "DEC-00",
      phase: "p1",
      title: "Replay default speed 60× for demos",
      decidedBy: "spm",
      witnesses: ["tl"],
      at: "2026-05-13T14:05:00Z",
      status: "superseded",
      supersededBy: null,
      verdict: "superseded",
      why: "Original demo used realtime; reviewers found it dull. 60× lets a 1h batch replay in 1min.",
      options: [
        { label: "1×", chosen: false },
        { label: "60×", chosen: true },
      ],
      affects: { plans: ["PL-02"], tasks: 1, messages: 0 },
      seal: "PM · 2026-05-13",
    },
  ];

  // ─── Verdicts queue ────────────────────────────────────────────────────
  const VERDICT_STATES = [
    { id: "needs-review", label: "Needs review", hue: 70 },
    { id: "in-test",      label: "In test",      hue: 220 },
    { id: "tested",       label: "Tested",       hue: 150 },
    { id: "done",         label: "Approved",     hue: 150 },
    { id: "rejected",     label: "Rejected",     hue: 25 },
    { id: "blocked",      label: "Blocked",      hue: 25 },
    { id: "superseded",   label: "Superseded",   hue: 80 },
  ];

  const VERDICTS = [
    { id: "V-201", target: { kind: "task", id: "W1.2" }, state: "needs-review", actor: "spm", awaiting: "human-raj", at: "2026-05-26T20:00:00Z", note: "Overstated claim — alloy/pharma loaders incomplete." },
    { id: "V-200", target: { kind: "plan", id: "PL-04" }, state: "needs-review", actor: "sdp", awaiting: "human-raj", at: "2026-05-27T09:42:00Z", note: "Phase 4 plan — six new modules." },
    { id: "V-198", target: { kind: "task", id: "P3.1" }, state: "needs-review", actor: "spm", awaiting: "tl", at: "2026-05-22T11:00:00Z", note: "Stage 3.1 sweep — please scope." },
    { id: "V-194", target: { kind: "message", id: "MSG-2026-05-27-0942" }, state: "needs-review", actor: "sdp", awaiting: "spm", at: "2026-05-27T09:42:00Z", note: "Phase 4 plan attached" },
    { id: "V-191", target: { kind: "task", id: "W1.5" }, state: "tested", actor: "be", awaiting: "spm", at: "2026-05-26T22:14:00Z", note: "f-string + model id fixed; replayed two batches." },
    { id: "V-188", target: { kind: "task", id: "W1.3" }, state: "done", actor: "tl", awaiting: null, at: "2026-05-15T18:54:00Z", note: "Reviewer code-audit pass." },
    { id: "V-186", target: { kind: "task", id: "A2.2" }, state: "tested", actor: "be", awaiting: "tl", at: "2026-05-19T13:57:00Z", note: "Azure OpenAI migration wired." },
    { id: "V-180", target: { kind: "task", id: "W1.1" }, state: "tested", actor: "spm", awaiting: null, at: "2026-05-13T20:00:00Z", note: "QA verified all 9 tables + idempotent init." },
    { id: "V-174", target: { kind: "plan", id: "PL-AR-01" }, state: "superseded", actor: "tl", awaiting: null, at: "2026-05-19T13:57:00Z", note: "Replaced by OpenAI-SDK plan." },
    { id: "V-170", target: { kind: "decision", id: "DEC-00" }, state: "superseded", actor: "spm", awaiting: null, at: "2026-05-15T11:14:00Z", note: "Replay default replaced." },
    { id: "V-160", target: { kind: "task", id: "W1.2" }, state: "rejected", actor: "spm", awaiting: "be", at: "2026-05-13T20:00:00Z", note: "Alloy 0 batches; pharma 0 rows." },
  ];

  // ─── Activity stream (cross-module) ────────────────────────────────────
  const ACTIVITY = [
    { at: "2026-05-27T11:12:00Z", actor: "human-raj", kind: "open", target: "Agentarium" },
    { at: "2026-05-27T09:42:00Z", actor: "sdp", kind: "message", target: "MSG-2026-05-27-0942", verb: "sent to SPM" },
    { at: "2026-05-27T09:30:00Z", actor: "sdp", kind: "plan", target: "PL-04", verb: "created" },
    { at: "2026-05-26T22:14:00Z", actor: "be", kind: "verdict", target: "W1.5", verb: "marked tested" },
    { at: "2026-05-26T19:13:00Z", actor: "human-raj", kind: "decision", target: "DEC-04", verb: "recorded" },
    { at: "2026-05-22T19:00:00Z", actor: "sdp", kind: "plan", target: "PL-03", verb: "updated" },
    { at: "2026-05-22T15:00:00Z", actor: "sdp", kind: "decision", target: "DEC-03", verb: "recorded" },
    { at: "2026-05-19T13:57:00Z", actor: "be", kind: "verdict", target: "A2.2", verb: "marked tested" },
    { at: "2026-05-18T17:30:00Z", actor: "tl", kind: "decision", target: "DEC-02", verb: "recorded" },
  ];

  window.AGENTARIUM = {
    NOW,
    PHASES: [
      { id: "p1", key: "P1", label: "Phase 1", name: "Week 1 Implementation",
        status: "completed", locked: true,  startedAt: "2026-05-08", closedAt: "2026-05-15",
        owner: "tl",   blurb: "DuckDB + data loaders + replay" },
      { id: "p2", key: "P2", label: "Phase 2", name: "Agentic Monitoring",
        status: "completed", locked: true,  startedAt: "2026-05-15", closedAt: "2026-05-21",
        owner: "sdp",  blurb: "Multi-agent system · Demo 1" },
      { id: "p3", key: "P3", label: "Phase 3", name: "Trust, Persona & ML",
        status: "in_progress", locked: false, startedAt: "2026-05-22",
        owner: "spm",  blurb: "Stabilize · RBAC · ask-agent" },
      { id: "p4", key: "P4", label: "Phase 4", name: "Agent Workspace",
        status: "todo", locked: false, startedAt: null,
        owner: "sdp",  blurb: "Agentarium shell · Planroom · Courier · Ledgers" },
    ],
    ROLES,
    CREWS: { count: 0, root: null, departments: [], personas: [] },
    PLANS,
    MESSAGES,
    DECISIONS,
    VERDICTS,
    VERDICT_STATES,
    ACTIVITY,
  };
})();
